### ISSUE TITLE
Add more training data to current model.

### ISSUE THREAD

**Issue by Tranquangdai** [undertheseanlp/word_tokenize#19]
I'm currently trying to reproduce your workflow. As far as I know, word_tokenize module of underthesea only use Vlsp2016 as training data. I think, training more data may help you better improve the model.
For the time being, we can incorporate Vlsp2013 data into the existing one.
So here is the step I took to preprocess data:
+) In the repository, for vlsp2016 you took the data in Conll format (kindly correct me if I'm wrong), then use preprocessing_vlsp2016.py to convert it to iob2 format, which produce 3 file in corpus folder: train, dev, test respectively. Here I'll use the same approach, since vlsp2013 use different data format, I wrote a different script to transform it to the same iob2 format as above.
+) Then, I would concatenate train2013 + train2016 -> train; dev2016 -> dev, test2013 + test2016 -> test.
Though, train-dev-test evaluate is a good strategy here. I think we would better off using grid search CV for hyper-parameter tuning the model.
Please discuss your idea here.

**Comment by rain1024** [comment]
@Tranquangdai Nice ideas. I agree with you about merging two dataset and using grid search CV. Just please notice that two datasets have a few different in tag sets.

**Comment by Tranquangdai** [comment]
of course, I've noticed that. That's why I add one more script to preprocess the vlsp2013.
I've fork your repo and refactor, re-structure your code. Here is link (please forgive me if the code is not nice enough) :))
https://github.com/Tranquangdai/word_tokenize

**Comment by rain1024** [comment]
Just look your repository. It's a good start for contributing. Just a little thought, please don't change `README.md` file because it will cause a problem with your merge requests in the future.

Please do your merge requests when you have some improvements. Contributions are always warmly welcome.
